name: emirates
description: An airline travel app for emirates company
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  provider: ^6.0.4
  get_it: ^7.2.0
  flutter_native_splash: ^2.2.14
  flutter_advanced_drawer: ^1.3.2
  barcode_widget: ^2.0.3
  pdf: ^3.8.4
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  open_app_file: ^4.0.1
  share_plus: ^6.3.0
  supabase_flutter: ^1.2.0
  multiple_result: ^1.0.4
  shared_preferences: ^2.0.15
  flutter_typeahead: ^4.1.1
  card_swiper: ^2.0.4
  awesome_notifications: ^0.7.4+1
  google_sign_in: ^5.4.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_small.png
  # branding: assets/dart.png
  # branding_mode: bottom

  color_dark: "#1d1d1f"
  image_dark: assets/images/logo_small.png
  # branding_dark: assets/dart_dark.png

  android_12:
    color: "#ffffff"
    image: assets/images/logo_small.png
    #branding: assets/dart.png

    color_dark: "#042a49"
    image_dark: assets/images/logo_small.png
    
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/destinations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic